### ISSUE TITLE
cannot build under ubuntu 20.04 - ithub/nvui/build/nvui_autogen/UVLADIE3JM/../../../src/cursor.hpp:8:10: fatal error: span: No such file or directory

### ISSUE THREAD

**Issue by kimusan** [rohit-px2/nvui#138]
I am trying to get nvui to compile in Ubuntu 20.04 but I am hitting this build error:
```
ithub/nvui/build/nvui_autogen/UVLADIE3JM/../../../src/cursor.hpp:8:10: fatal error: span: No such file or directory
```
the cmake process completedd without error (both with and without vcpkg). 

any ideas?

**Comment by rohit-px2** [comment]
`<span>` is a c++20 header file, so you would probably need to update your c++ version.
